### ISSUE TITLE
Setting auth endpoint

### ISSUE THREAD

**Issue by kleenkanteen** [Tasin5541/NextJs-Messenger-Clone#17]
In https://github.com/Tasin5541/NextJs-Messenger-Clone/blob/main/src/app/libs/pusher.ts, line 21, why do you use "channelAuthorization" when the docs use "userAuthorization"?: https://pusher.com/docs/channels/using_channels/user-authentication/.

**Comment by Tasin5541** [comment]
The link you provided is for User Authentication. We don't need pusher's authentication system, because we're authenticating the users ourselves. What we need is user authorization (whether the user is authorized to access a channel), which is covered here: https://pusher.com/docs/channels/server_api/authorizing-users/

If you're confused about the difference in authentication and authorization, have a look at this:
https://auth0.com/docs/get-started/identity-fundamentals/authentication-and-authorization

**Comment by kleenkanteen** [comment]
Ah right

**Comment by kleenkanteen** [comment]
Also why did you put that endpoint under the pages router instead of the app router?

**Comment by Tasin5541** [comment]
> Also why did you put that endpoint under the pages router instead of the app router?

That is because pusher did not support the app router at the time. Not sure if it does now, I haven't seen any update on that yet.

**Comment by kleenkanteen** [comment]
@Tasin5541  How do you know if it supports app router or not?

**Comment by Tasin5541** [comment]
> Isn't auth a matter of a simple endpoint?

A valid point. Unfortunately I do not have the answer at the moment. It was a trial and error approach. As there is no official doc supporting NextJs implementation, it's tough to get an answer. Maybe this boils down to the internal structure of NextJs's page api and route handler. If I get an answer, I'll update the thread. If you find out anything, please do update the thread as well.

> Why not prefixed pusherKey with "private" so it is a private channel?

That would obviously be a more secure approach. We're handling the channel authorization from our side instead of pusher for the following reasons:
- So the application is less dependent on a 3rd party tool
- Any future change in authorization process from pusher does not break the application 

But do keep in mind, production grade applications will have their own server and channel system with their own security measures. Pusher is used here just to mimic a part of that process.

**Comment by kleenkanteen** [comment]
I was able to host the auth endpoint on a app router endpoint. Worked perfectly fine (locally at least). 

For private channels, we still handle channel authorization from our side to a certain extent though. Pusher hits the endpoint you defined in "channelAuthorization", your endpoint checks if the user can get access, then tells pusher to authorize the user or not to the channel.
